---
- hosts: "localhost"
  connection: "local"
  gather_facts: false
  become: true
  become_method: "sudo"

  vars:
    ansible_python_interpreter: "/usr/bin/python2.7"

  roles:
    - ansible-role-pki
    - ansible-role-cons3rt-cli 

